language: rust
rust:
 - 1.19.0
 - stable
cache: cargo
services:
 - postgresql
before_script:
 - cargo update || true
 - echo "DATABASE_URL=postgres://localhost/rphotos" > .env
 - cargo install -v diesel_cli --no-default-features --features postgres || true
 - $HOME/.cargo/bin/diesel setup
matrix:
  include:
   - rust: nightly
     env: TASK=rustfmt
     before_script:
      - export PATH="$PATH:$HOME/.cargo/bin"
      - CFG_RELEASE_CHANNEL=nightly cargo install -f rustfmt-nightly
     script:
      - cargo fmt -- --unstable-features --write-mode=diff
