[package]
name = "rphotos"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
diesel_codegen_syntex = { version = "^0.9", features = ["postgres", "syntex"] }
ructe = "^0.2.4"
rsass = "*"

[[bin]]
name = "rphotoserver"
path = "src/main.rs"

[[bin]]
name = "rphotosadm"
path = "src/rphotosadm.rs"

[dependencies]
nickel = "^0.9"
nickel-jwt-session = "^0.5"
env_logger = "*"
log = "*"
chrono = "^0.2" # Must match version used by diesel
clap = "^2.19"
rustc-serialize = "*"
typemap = "*"
plugin = "*"
image = "*"
hyper = "^0.9"
time = "*"
xml-rs = "*"
rexif = "*"
diesel = { version = "^0.9", default-features = false, features = ["chrono", "postgres"] }
dotenv = "*"
r2d2 = "*"
nickel-diesel = "*"
r2d2-diesel = "^0.9"
djangohashers = "*"
rand = "*"
memcached-rs = "^0.1"
flate2 = "*"
brotli2 = "*"
