[package]
name = "rphotos"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
sass-rs = "*"
sass-sys = "*"
md5 = "*"
rustc-serialize = "*"
flate2 = "*"
brotli2 = "*"
syntex = { version = "<0.39.0" }
diesel_codegen_syntex = { version = "0.7", features = ["postgres", "syntex"] }
dotenv_codegen = { version = "<0.9.1" }

[[bin]]
name = "rphotoserver"
path = "src/main.rs"

[[bin]]
name = "readkpa"
path = "src/readkpa.rs"

[[bin]]
name = "findphotos"
path = "src/findphotos.rs"

[[bin]]
name = "public_from_list"
path = "src/public_from_list.rs"

[[bin]]
name = "setpassword"
path = "src/setpassword.rs"

[dependencies]
nickel = ">= 0.8.1"
nickel-jwt-session = "*"
env_logger = "*"
log = "*"
chrono = "*"
rustc-serialize = "*"
typemap = "*"
plugin = "*"
image = "*"
hyper = "0.8.1"
time = "*"
xml-rs = "*"
rexif = "0.3.3"
diesel = { version = "0.7", default-features = false, features = ["chrono", "postgres"] }
dotenv = "0.8"
r2d2 = "*"
nickel-diesel = "0.3"
r2d2-diesel = "*"
djangohashers = "*"
rand = "*"
