[package]
name = "rphotos"
version = "0.4.27-PRE"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { version = "^0.5.0", features = ["sass", "mime02"] }

[dependencies]
nickel = "~0.10.0"
nickel-jwt-session = "~0.10.0"
hyper = "~0.10.0"
env_logger = "*"
libc = "*"
log = "*"
chrono = "~0.4.0" # Must match version used by diesel
clap = { version = "^2.19", features = [ "color", "wrap_help" ] }
typemap = "*"
plugin = "*"
image = "0.21"
time = "*"
kamadak-exif = "~0.3.0"
diesel = { version = "1.4.0", features = ["r2d2", "chrono", "postgres"] }
dotenv = "0.13.0"
djangohashers = "*"
rand = "0.6.5"
memcached-rs = "0.4.1"
flate2 = "^1.0.0"
brotli2 = "*"
mime = "0.2.6"
regex = "*"
slug = "0.1"
reqwest = "0.9"
serde_json = "1.0"
