[package]
name = "rphotos"
version = "0.4.5-PRE"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { version = "^0.3.10", features = ["sass", "mime02"] }

[dependencies]
nickel = "~0.10.0"
nickel-jwt-session = "~0.10.0"
hyper = "~0.10.0"
env_logger = "*"
libc = "*"
log = "*"
chrono = "~0.4.0" # Must match version used by diesel
clap = "^2.19, < 2.28"
typemap = "*"
plugin = "*"
image = "^0.16.0"
time = "*"
rexif = "^0.3.4"
diesel = { version = "~0.16.0", features = ["chrono", "postgres"] }
diesel_codegen = { version = "~0.16.0", features = ["postgres"] }
r2d2-diesel = "~0.16.0"
r2d2 = "0.7.4" # Must match version used by r2d2-diesel
rustc-serialize = "0.3.24" # Must match version used by nickel
dotenv = "~0.10.1"
djangohashers = "*"
rand = "~0.3.18"
memcached-rs = "^0.1"
flate2 = "^1.0.0"
brotli2 = "*"
mime = "0.2.6"
regex = "*"
slug = "0.1"
