[package]
name = "rphotos"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

[[bin]]
name = "rphotos"
path = "src/main.rs"

[[bin]]
name = "readkpa"
path = "src/readkpa.rs"

[[bin]]
name = "findphotos"
path = "src/findphotos.rs"

[dependencies.rustorm]
version = "*"
default-features = false

[dependencies]
nickel = "*"
env_logger = "*"
log = "*"
chrono = "*"
rustc-serialize = "*"
typemap = "*"
plugin = "*"
image = "*"
hyper = "*"
time = "*"
xml-rs = "*"
rexif = "0.3.3"
