[package]
name = "rphotos"
version = "0.3.6"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { version = "^0.3.6", features = ["sass", "mime02"] }

[dependencies]
nickel = "~0.10.0"
nickel-jwt-session = "~0.10.0"
hyper = "~0.10.0"
env_logger = "*"
libc = "*"
log = "*"
chrono = "~0.4.0" # Must match version used by diesel
clap = "^2.19"
typemap = "*"
plugin = "*"
image = "^0.16.0"
time = "*"
rexif = "^0.3.4"
diesel = { version = "~0.16.0", features = ["chrono", "postgres"] }
diesel_codegen = { version = "~0.16.0", features = ["postgres"] }
r2d2-diesel = "~0.16.0"
r2d2 = "*"
rustc-serialize = "0.3.24" # Must match version used by nickel
dotenv = "~0.10.1"
djangohashers = "*"
rand = "*"
memcached-rs = "^0.1"
flate2 = "*"
brotli2 = "*"
mime = "0.2.6"
regex = "*"
