[package]
name = "rphotos"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"
# build = "src/sassify.rs"

[build-dependencies]
sass-rs = "*"
sass-sys = "*"
md5 = "*"
rustc-serialize = "*"
flate2 = "*"
brotli2 = "*"
syntex = { version = "0.31.0", optional = true }
diesel_codegen = { version = "0.6.2", default-features = false, features = ["postgres"] }
dotenv_codegen = { version = "0.8.1",  optional = true }

[[bin]]
name = "rphotoserver"
path = "src/main.rs"

[[bin]]
name = "readkpa"
path = "src/readkpa.rs"

[[bin]]
name = "findphotos"
path = "src/findphotos.rs"

[[bin]]
name = "setpassword"
path = "src/setpassword.rs"

[dependencies]
nickel = ">= 0.8.1"
nickel-jwt-session = "*"
env_logger = "*"
log = "*"
chrono = "*"
rustc-serialize = "*"
typemap = "*"
plugin = "*"
image = "*"
hyper = "0.8.1"
time = "*"
xml-rs = "*"
rexif = "0.3.3"
diesel = { version = "0.6.2", default-features = false, features = ["chrono", "postgres"] }
diesel_codegen = { version = "0.6.2", default-features = false, features = ["postgres"] }
dotenv = "0.8.0"
dotenv_macros = { version = "0.8.0", optional = true }
r2d2 = "*"
nickel-diesel = "0.2.0"
r2d2-diesel = "*"
djangohashers = "*"
rand = "*"

[features]
default = ["with-syntex"]
with-syntex = ["syntex", "diesel_codegen/with-syntex", "dotenv_codegen"]
nightly = ["diesel/unstable", "diesel_codegen/nightly", "dotenv_macros"]
