[package]
name = "rphotos"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
sass-rs = "*"
sass-sys = "*"
md5 = "*"
rustc-serialize = "*"
flate2 = "*"
brotli2 = "*"
syntex = "^0.44"
diesel_codegen_syntex = { version = "^0.8", features = ["postgres", "syntex"] }
dotenv_codegen = "*"
ructe = "^0.1.2"

[[bin]]
name = "rphotoserver"
path = "src/main.rs"

[[bin]]
name = "rphotosadm"
path = "src/rphotosadm.rs"

[[bin]]
name = "readkpa"
path = "src/readkpa.rs"

[[bin]]
name = "findphotos"
path = "src/findphotos.rs"

[[bin]]
name = "public_from_list"
path = "src/public_from_list.rs"

[[bin]]
name = "setpassword"
path = "src/setpassword.rs"

[dependencies]
nickel = "^0.9"
nickel-jwt-session = "^0.5"
env_logger = "*"
log = "*"
chrono = "*"
clap = "^2.18"
rustc-serialize = "*"
typemap = "*"
plugin = "*"
image = "*"
hyper = "*"
time = "*"
xml-rs = "*"
rexif = "0.3.3"
diesel = { version = "0.8", default-features = false, features = ["chrono", "postgres"] }
dotenv = "^0.8"
r2d2 = "*"
nickel-diesel = "*"
r2d2-diesel = "*"
djangohashers = "*"
rand = "*"
memcached-rs = "^0.1"
