[package]
name = "rphotos"
version = "0.1.0"
authors = ["Rasmus Kaj <kaj@kth.se>"]

build = "src/build.rs"

[build-dependencies]
ructe = { version = "^0.3.2", features = ["sass", "mime02"] }

[[bin]]
name = "rphotoserver"
path = "src/main.rs"

[[bin]]
name = "rphotosadm"
path = "src/rphotosadm.rs"

[dependencies]
nickel = "~0.9.0"
nickel-jwt-session = "^0.6"
env_logger = "*"
log = "*"
chrono = "^0.3" # Must match version used by diesel
clap = "^2.19"
typemap = "*"
plugin = "*"
image = "*"
hyper = "^0.9"
time = "*"
xml-rs = "*"
rexif = "^0.3.4"
diesel = { version = "^0.12", features = ["chrono", "postgres"] }
diesel_codegen = { version = "^0.12", features = ["postgres"] }
dotenv = "^0.8"
r2d2-diesel = "^0.12"
r2d2 = "*"
djangohashers = "*"
rand = "*"
memcached-rs = "^0.1"
flate2 = "*"
brotli2 = "*"
mime = "0.2.6"
